# Generated by Django 5.2.4 on 2025-08-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=9, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='GraduacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(max_length=6, verbose_name='Faixa')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPagamentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=15, verbose_name='Método de pagamento Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(max_length=15, verbose_name='Mensal ou Plano')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Pago')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_aluno/')),
                ('genero_aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.generoaluno', verbose_name='Gênero')),
                ('faixa_aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.graduacaoaluno', verbose_name='Faixa')),
                ('metodo_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.metodopagamentoaluno', verbose_name='Método de Pagamento')),
                ('pagamento_aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.pagamentoaluno', verbose_name='Mensal ou Plano')),
            ],
        ),
    ]
