# Generated by Django 5.2.4 on 2025-08-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_etaria', models.CharField(max_length=10, verbose_name='Categoria Etária')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupo_idade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.tipoturmaaluno', verbose_name='Categoria Etária'),
        ),
    ]
