# Generated by Django 5.2.4 on 2025-08-06 16:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_tipoturmaaluno_aluno_grupo_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', verbose_name='Telefone de Contato'),
        ),
    ]
