# Generated by Django 5.2.4 on 2025-08-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='proximo_pagamento',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Próximo Pagamento'),
        ),
    ]
