# Generated by Django 5.2.4 on 2025-08-07 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_aluno_proximo_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor_produto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('metodo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.metodopagamentoaluno')),
            ],
        ),
    ]
