# Generated by Django 5.2.4 on 2025-08-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alunos.aluno')),
                ('metodo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.metodopagamentoaluno')),
            ],
        ),
    ]
