# Generated by Django 5.2.4 on 2025-08-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_pagamentomensalidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagamentoMensalidade',
        ),
    ]
