# Generated by Django 5.2.4 on 2025-08-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_delete_pagamentomensalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_despesa', models.CharField(max_length=100, verbose_name='Descrição despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_despesa', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('data_despesa', models.DateField(auto_now_add=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.despesamensal', verbose_name='Despesa')),
            ],
        ),
    ]
