# Generated by Django 5.2.4 on 2025-08-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_despesamensal_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Qauntidade'),
        ),
    ]
