# Generated by Django 5.2.4 on 2025-08-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
