# Generated by Django 5.2.4 on 2025-08-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_produto_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_total',
        ),
    ]
