# Generated by Django 5.2.4 on 2025-08-20 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_aluno_cadastrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
