# Generated by Django 5.2.4 on 2025-09-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_produto_quantidade_produto_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacaoaluno',
            name='faixa',
            field=models.CharField(max_length=30, verbose_name='Faixa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='tipoturmaaluno',
            name='categoria_etaria',
            field=models.CharField(max_length=30, verbose_name='Categoria Etária'),
        ),
    ]
