# Generated by Django 5.2.4 on 2025-09-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0015_alter_graduacaoaluno_faixa_alter_produto_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='faixa_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.graduacaoaluno', verbose_name='Faixa'),
        ),
        migrations.AlterField(
            model_name='tipoturmaaluno',
            name='categoria_etaria',
            field=models.CharField(max_length=30, verbose_name='Categoria Etária/Esporte'),
        ),
    ]
