# Generated by Django 5.2.4 on 2025-09-06 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_alter_aluno_faixa_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, default='---', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='grupo_idade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.tipoturmaaluno', verbose_name='Categoria'),
        ),
    ]
