# Generated by Django 5.2.4 on 2025-09-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0017_alter_aluno_email_alter_aluno_grupo_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, default='Não informado', max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
